name: Firebase Deploy

on:
  push:
    branches:
      - principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Firebase
        uses: w9j/firebase-action@v1.1.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN:...
env:
  FIREBASE_TOKEN: 1//0HGe_eVsd003nCgYIARAAGBESNwf-L9I1r1TFbBOyeLNLoNHKTQ_iERqeZhK9CI-2u6LSo_pWkSw_KNLwCoPUTNx1tGxcrtMZZKM
